include: package:lint/analysis_options.yaml

analyzer:
  errors:
    avoid_print: ignore
    constant_identifier_names: true

  exclude:
    - "**/*.gr.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.dart"